title: DUBOIS
description: A new introductory, interdisciplinary course for computing, data science, and society.
theme: just-the-docs

url: "https://dubois-ctds.github.io" # the base hostname & protocol for your site, e.g. http://example.com

aux_links:
  # Template Repository: https://github.com/just-the-docs/just-the-docs-template
